config/routes.rb
Inteligencia::Application.routes.draw do
  resources :locations
  resources :gas_stations  
  root :to => "dashboard#index" 
end

app/models/gas_station.rb
class GasStation < ActiveRecord::Base
  has_many :week_collections, :dependent => :destroy
  has_one :location, :dependent => :destroy

  attr_accessible :bairro, :distribuidora, :endereco, :nome, :municipio, :estado
  
  validates_presence_of :nome
  
  def self.search(search)
    if (search && search.strip.length > 0)
      search = search.downcase
      search = "'%"+ search + "%'"
      joins(:week_collections).where("lower(estado) LIKE #{search} OR lower(municipio) LIKE #{search}
      OR lower(bairro) LIKE #{search}").order('week_collections.preco_venda DESC')
    else
      joins(:week_collections).order('week_collections.preco_venda DESC')
    end
  end
  
  def complete_address
    "#{endereco}, #{bairro}, #{municipio} - #{estado}"
  end
  
end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :gas_station
  attr_accessible :address, :latitude, :longitude
  geocoded_by :address
  after_validation :geocode, :if => :address_changed?  
end

app/models/week_collection.rb
class WeekCollection < ActiveRecord::Base
  belongs_to :gas_station
  attr_accessible :cod_semana, :data, :fornecedor, :gas_station_id, :modalidade, :preco_compra, :preco_venda

  validates_presence_of :gas_station_id, :cod_semana
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @bairro_maior_media = WeekCollection.select('gas_stations.bairro, avg(preco_venda)').joins(:gas_station).group('gas_stations.bairro').order('avg DESC').limit(5)
    @bandeira_maior_media = WeekCollection.select('gas_stations.distribuidora, avg(preco_venda)').joins(:gas_station).group('gas_stations.distribuidora').order('avg DESC').limit(5)
    @maiores_precos_bandeira_branca = GasStation.select('nome, week_collections.preco_compra, week_collections.fornecedor').joins(:week_collections).where("lower(distribuidora) = 'branca'").order('preco_compra DESC').limit(5)
    @menores_precos_bandeira_branca = GasStation.select('nome, week_collections.preco_compra, week_collections.fornecedor').joins(:week_collections).where("lower(distribuidora) = 'branca' AND preco_compra > 0").order('preco_compra ASC').limit(5)
    # @top_5_distribuidores = GasStation.select('distribuidora, count(*)').group('distribuidora').where("lower(distribuidora) = 'branca'").order('count DESC').limit(5)
    @top_5_fornecedores = WeekCollection.select('fornecedor, count(*)').joins(:gas_station).group('fornecedor').where("lower(gas_stations.distribuidora) = 'branca'").order('count DESC').limit(5)
  end
end

app/controllers/gas_stations_controller.rb
class GasStationsController < ApplicationController
  # GET /gas_stations
  # GET /gas_stations.json
  def index
    # @gas_stations = GasStation.order('nome')
    
    @gas_stations = GasStation.search(params[:search])
      
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @gas_stations }
    end
  end

  # GET /gas_stations/1
  # GET /gas_stations/1.json
  def show
    @gas_station = GasStation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gas_station }
    end
  end

  # GET /gas_stations/new
  # GET /gas_stations/new.json
  def new
    @gas_station = GasStation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gas_station }
    end
  end

  # GET /gas_stations/1/edit
  def edit
    @gas_station = GasStation.find(params[:id])
  end

  # POST /gas_stations
  # POST /gas_stations.json
  def create
    @gas_station = GasStation.new(params[:gas_station])

    respond_to do |format|
      if @gas_station.save
        format.html { redirect_to @gas_station, notice: 'Gas station was successfully created.' }
        format.json { render json: @gas_station, status: :created, location: @gas_station }
      else
        format.html { render action: "new" }
        format.json { render json: @gas_station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /gas_stations/1
  # PUT /gas_stations/1.json
  def update
    @gas_station = GasStation.find(params[:id])

    respond_to do |format|
      if @gas_station.update_attributes(params[:gas_station])
        format.html { redirect_to @gas_station, notice: 'Gas station was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gas_station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gas_stations/1
  # DELETE /gas_stations/1.json
  def destroy
    @gas_station = GasStation.find(params[:id])
    @gas_station.destroy

    respond_to do |format|
      format.html { redirect_to gas_stations_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @locations }
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @location = Location.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/new
  # GET /locations/new.json
  def new
    @location = Location.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/1/edit
  def edit
    @location = Location.find(params[:id])
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(params[:location])

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render json: @location, status: :created, location: @location }
      else
        format.html { render action: "new" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /locations/1
  # PUT /locations/1.json
  def update
    @location = Location.find(params[:id])

    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/gas_stations_helper.rb
module GasStationsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/dashboard/_geral.html.erb
<div class="row-fluid">
	<div class="span6">
		<h4>Bairro com maior média</h4>
		<table class="table table-striped table-bordered">
		  <thead>
			<th>Bairro</th>
			<th>Média de venda</th>
		  </thead>
		  <tbody>
		    <% @bairro_maior_media.each do |week_collection| %>
		      <tr>
		        <td><%= week_collection.bairro %></td>
		        <td><%= week_collection.avg.to_f.round(3) %></td>
		      </tr>
		    <% end %>
		  </tbody>
		</table>		
	</div>
	<div class="span6">
		<h4>Bandeira com maior média</h4>
		<table class="table table-striped table-bordered">
		  <thead>
			<th>Bandeira</th>
			<th>Média de venda</th>
		  </thead>
		  <tbody>
		    <% @bandeira_maior_media.each do |week_collection| %>
		      <tr>
		        <td><%= week_collection.distribuidora %></td>
		        <td><%= week_collection.avg.to_f.round(3) %></td>
		      </tr>
		    <% end %>
		  </tbody>
		</table>		
	</div>
</div>
<div class="row-fluid">
	<div class="span6">
		<h4>Maiores preços bandeira branca</h4>
		<table class="table table-striped table-bordered">
		  <thead>
			<th>Nome</th>
			<th>Preço de Compra</th>
			<th>Fornecedor</th>
		  </thead>			
		  <tbody>
		    <% @maiores_precos_bandeira_branca.each do |gas_station| %>
		      <tr>
		        <td><%= gas_station.nome %></td>
		        <td><%= gas_station.preco_compra.to_f.round(3) %></td>
		        <td><%= gas_station.fornecedor %></td>
		      </tr>
		    <% end %>
		  </tbody>
		</table>				
	</div>
	<div class="span6">
		<h4>Menores preços bandeira branca</h4>
		<table class="table table-striped table-bordered">
		  <thead>
			<th>Nome</th>
			<th>Preço de Compra</th>
			<th>Fornecedor</th>
		  </thead>			
		  <tbody>
		    <% @menores_precos_bandeira_branca.each do |gas_station| %>
		      <tr>
		        <td><%= gas_station.nome %></td>
		        <td><%= gas_station.preco_compra.to_f.round(3) %></td>
		        <td><%= gas_station.fornecedor %></td>
		      </tr>
		    <% end %>
		  </tbody>
		</table>		
	</div>
</div>
<div class="row-fluid">
	<!-- <div class="span6">
		<h4>Top 5 distribuidores bandeira branca</h4>
		<table class="table table-striped">
		  <thead>
			<th>Distribuidora</th>
			<th>Quantidade de postos</th>
		  </thead>			
		  <tbody>
		    < % @top_5_distribuidores.each do |gas_station| %>
		      <tr>
		        <td>< %= gas_station.distribuidora %></td>
		        <td>< %= gas_station.count %></td>
		      </tr>
		    < % end %>
		  </tbody>
		</table>		
	</div> -->
	<div class="span6">
		<h4>Top 5 fornecedor bandeira branca</h4>
		<table class="table table-striped table-bordered">
		  <thead>
			<th>Fornecedor</th>
			<th>Quantidade de postos</th>
		  </thead>			
		  <tbody>
		    <% @top_5_fornecedores.each do |week_collection| %>
		      <tr>
		        <td><%= week_collection.fornecedor %></td>
		        <td><%= week_collection.count %></td>
		      </tr>
		    <% end %>
		  </tbody>
		</table>				
	</div>
</div>

app/views/dashboard/_mapa.html.erb
<div class="row-fluid">
	<div class="span4">
		<h5>Mapa</h5>
				<%= image_tag( "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{Location.last.latitude}%2C#{Location.last.longitude}") %>
	</div>
	<div class="span8">
		<h5>Postos</h5>
		<ul>
		<% for location in Location.last.nearbys(20) %>
		  <li><%= link_to location.gas_station.nome, gas_station_path(location.gas_station) %>, <%= location.gas_station.endereco %></li>
		<% end %>
		</ul>
		
	</div>
</div>

app/views/dashboard/index.html.erb
<legend>Dashboard</legend>

<ul class="nav nav-tabs" id="myTab">
	<li class="active"><a href="#geral_tab" data-toggle="tab"><%= t('.geral')%></a></li>
	<li><a href="#foursquare_tab" data-toggle="tab"><%= t('.foursquare')%></a></li>				
	<li><a href="#apontador_tab" data-toggle="tab"><%= t('.apontador')%></a></li>				
	<li><a href="#mapa_tab" data-toggle="tab"><%= t('.Mapa')%></a></li>				
</ul>


<div class="tab-content">
	<div class="tab-pane active" id="geral_tab">
		<!-- < % = render :partial => 'geral', :locals => {:model_class => model_class} %> -->
		<%= render :partial => 'geral'%>
	</div>
	
	<div class="tab-pane" id="foursquare_tab">
		<%= render :partial => 'foursquare' %>
	</div>
	
	<div class="tab-pane" id="apontador_tab">
		<%= render :partial => 'apontador'%>
	</div>
	
	<div class="tab-pane" id="mapa_tab">
		<%= render :partial => 'mapa'%>
	</div>
	
</div>

app/views/gas_stations/_form.html.erb
<%= simple_form_for @gas_station, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :nome %>
  <%= f.input :endereco %>
  <%= f.input :bairro %>
  <%= f.input :distribuidora %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                gas_stations_path, :class => 'btn' %>
  </div>
<% end %>

app/views/gas_stations/edit.html.erb
<%- model_class = GasStation -%>

  <legend><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></legend>
</div>
<%= render :partial => 'form' %>

app/views/gas_stations/index.html.erb
<%- model_class = GasStation -%>
<div class="pull-right">
	<form class="form-search">
		<%= text_field_tag :search, params[:search], :placeholder => "UF, Município ou Bairro" %>
		<button type="submit" class="btn"><i class='icon-search'></i></button>
	</form>
</div>	

<legend><%=t '.title', :default => model_class.model_name.human.pluralize %></legend>

<div class="pull-right" style="margin: -15px 0 5px 0">
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_gas_station_path,
            :class => 'btn btn-primary' %>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:endereco) %></th>
      <th><%= model_class.human_attribute_name(:bairro) %></th>
      <th><%= model_class.human_attribute_name(:municipio) %></th>
      <th><%= model_class.human_attribute_name(:estado) %></th>
      <th><%= model_class.human_attribute_name(:distribuidora) %></th>
      <th><%= model_class.human_attribute_name(:preco_venda) %></th>
      <th><%= model_class.human_attribute_name(:preco_compra) %></th>
      <th><%= model_class.human_attribute_name(:fornecedor) %></th>
      <th><%= model_class.human_attribute_name(:data_coleta) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @gas_stations.each do |gas_station| %>
      <tr>
        <td><%= link_to gas_station.nome, gas_station_path(gas_station) %></td>
        <td><%= gas_station.endereco %></td>
        <td><%= gas_station.bairro %></td>
        <td><%= gas_station.municipio %></td>
        <td><%= gas_station.estado %></td>
        <td><%= gas_station.distribuidora %></td>
        <td><%= gas_station.week_collections.last.preco_venda %></td>
        <td><%= gas_station.week_collections.last.preco_compra %></td>
        <td><%= gas_station.week_collections.last.fornecedor %></td>
        <td><%= l gas_station.week_collections.last.data %></td>
        <td>
	
	      <%= link_to edit_gas_station_path(gas_station) do %>
	         <i class="icon-pencil"></i>
	      <% end %>

	      <%= link_to gas_station_path(gas_station), method: :delete, data: { confirm: 'Deseja realmente remover este registro?' } do %>
	        <i class="icon-remove"></i>
	      <% end %>
	
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/gas_stations/new.html.erb
<%- model_class = GasStation -%>

  <legend><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></legend>
</div>
<%= render :partial => 'form' %>

app/views/gas_stations/show.html.erb
<%- model_class = GasStation -%>

<legend><%=t '.title', :default => model_class.model_name.human %></legend>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nome) %>:</strong></dt>
  <dd><%= @gas_station.nome %></dd>
  <dt><strong><%= model_class.human_attribute_name(:endereco) %>:</strong></dt>
  <dd><%= @gas_station.endereco %></dd>
  <dt><strong><%= model_class.human_attribute_name(:bairro) %>:</strong></dt>
  <dd><%= @gas_station.bairro %></dd>
  <dt><strong><%= model_class.human_attribute_name(:distribuidora) %>:</strong></dt>
  <dd><%= @gas_station.distribuidora %></dd>
</dl>

<div class="row-fluid">
	<div class="span6">
		<h5>Dados da semana</h5>
		<table class="table table-striped table-bordered">
			<tbody>
				<tr>
					<td><%= model_class.human_attribute_name(:preco_venda) %></td>
					<td><%= @gas_station.week_collections.last.preco_venda %></td>
				</tr>
				<tr>
					<td><%= model_class.human_attribute_name(:preco_compra) %></td>
					<td><%= @gas_station.week_collections.last.preco_compra %></td>
				</tr>
				<tr>
					<td><%= model_class.human_attribute_name(:fornecedor) %></td>
					<td><%= @gas_station.week_collections.last.fornecedor %></td>
				</tr>
				<tr>
					<td><%= model_class.human_attribute_name(:data_coleta) %></td>
					<td><%= l @gas_station.week_collections.last.data %></td>
				</tr>
			</tbody>
		</table>
	</div>
	<div class="span6">
		<div id="price_chart" style="width:560px; height:300px;">

		</div>
	</div>	
</div>
<legend></legend>
<div class="row-fluid">	
	<div class="span4">
		<h5>Mapa</h5>
		<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@gas_station.location.latitude}%2C#{@gas_station.location.longitude}" %>
	</div>
	<div class="span8">
		<h5>Postos próximos (1km)</h5>
		<ul>
		<% for location in @gas_station.location.nearbys(1) %>
		  <li><%= link_to location.gas_station.nome, gas_station_path(location.gas_station) %>, <%= location.gas_station.endereco %> (<%= location.distance.to_f.round(2) %> KM)</li>
		<% end %>
		</ul>
	</div>
</div>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              gas_stations_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_gas_station_path(@gas_station), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              gas_station_path(@gas_station),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Inteligencia" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>


    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
          </a>
          <a class="brand" href="#">Inteligência</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
			  <li><%= link_to t('.dashboard'), root_path %></li>
              <li><%= link_to "Postos", "/gas_stations"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
          <%= bootstrap_flash %>
          <%= yield %>
      </div><!--/row-->

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
	<%= javascript_include_tag "jquery.1.9.1.min", "rails", "highcharts" %>
	<%= javascript_include_tag "jquery.1.9.1.min", "rails", "highstock" %>
	
	<script type="text/javascript" charset="utf-8">
		$(function() {
			new Highcharts.Chart({
				chart: {
					renderTo: "price_chart"
				},
				title: {
					text: "Evolução do Preço"
				},
				xAxis: {
					type: "datetime"
				},
				yAxis: {
					title: {
						text: "Reais"
					}
				},
				series: [{
					name: "Preço de venda",
					pointInterval: <%= 1.week * 1000 %>,
					pointStart: <%= 4.weeks.ago.to_i * 1000 %>,
					data: [2.8, 2.85, 2.89, 2.95, 2.85]
				}]
			});
		});
	</script>

  </body>
</html>

app/views/locations/_form.html.erb
<%= simple_form_for @location, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :address %>
  <%= f.input :latitude %>
  <%= f.input :longitude %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                locations_path, :class => 'btn' %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<%- model_class = Location -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/locations/index.html.erb
<%- model_class = Location -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:latitude) %></th>
      <th><%= model_class.human_attribute_name(:longitude) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= link_to location.id, location_path(location) %></td>
        <td><%= location.address %></td>
        <td><%= location.latitude %></td>
        <td><%= location.longitude %></td>
        <td><%=l location.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_location_path(location), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      location_path(location),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_location_path,
            :class => 'btn btn-primary' %>

app/views/locations/new.html.erb
<%- model_class = Location -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Address:</b>
  <%= @location.address %>
</p>

<p>
  <b>Latitude:</b>
  <%= @location.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @location.longitude %>
</p>

<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@location.latitude}%2C#{@location.longitude}" %>

<h3> Postos por perto </h3>
<ul>
<% for location in @location.nearbys(10) %>
  <li><%= link_to location.address, location %> (<%= location.distance %> KM)</li>
<% end %>
</ul>

<p>
<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>
</p>

app/views/postos/_form.html.erb
<%= simple_form_for @posto, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :nome %>
  <%= f.input :endereco %>
  <%= f.input :bairro %>
  <%= f.input :distribuidora %>
  <%= f.input :preco_venda %>
  <%= f.input :preco_compra %>
  <%= f.input :modalidade %>
  <%= f.input :fornecedor %>
  <%= f.input :data_coleta %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                postos_path, :class => 'btn' %>
  </div>
<% end %>